# -*- coding: utf-8 -*-
"""Repeating Decimal.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HZKlPBU3CIh9kj7f-Nrykd1f4gXiYlFg
"""

def repeating_decmials(x,y):
    if not (x, int) or not (y, int):
        raise ValueError("num and den must be integers")
    if y == 0:
        raise ValueError("den cannot be zero")
    result = ""
x=int(input("enter a numerator:"))
y=int(input("enter a denominator:"))
res=x/y
print(res)

